config/routes.rb
Rails.application.routes.draw do
  root 'kittens#index'
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

    def index
        @kittens = Kitten.all

        respond_to do |format|
            format.html
            format.json { render :json => @kittens }
        end

    end

    def new 
        @kitten = Kitten.new
    end

    def create
        @kitten = Kitten.create(kitten_params)

        if @kitten.save
            redirect_to @kitten
            flash[:success] = "Your kitten has been created!"
        else render 'new'
            flash.now[:alert] = "Your kitten doesn't wanna come into this world"
        end
    end

    def show 
        @kitten = Kitten.find(params[:id])

        respond_to do |format|
            format.html
            format.json { render :json => @kittens }
        end 
        
    end

    def edit
        @kitten = Kitten.find(params[:id])
    end

    def update
        @kitten = Kitten.find(params[:id])
        if @kitten.update(kitten_params)
            redirect_to @kitten
            flash[:success] = "Your kitten has had a bit of a change..."           
        else render 'edit'
            flash.now[:alert] = "Stop trying to change your kitten! It's not working..."   
        end
    end

    def destroy
        @kitten = Kitten.find(params[:id])
        if @kitten.destroy
            redirect_to root_path
            flash[:success] = "Your kitty has been put to sleep"
        else    
            render 'show'
            flash.now[:alert] = "Your kitty couldn't be put to sleep"
        end
    end

    private
        def kitten_params
            params.require(:kitten).permit(:name, :age, :cuteness, :softness)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with(model: @kitten) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :age %>
    <%= f.text_field :age %>

    <%= f.label :cuteness %>
    <%= f.text_field :cuteness %>

    <%= f.label :softness %>
    <%= f.text_field :softness %>

    <%= f.submit %>
<% end %>

app/views/kittens/edit.html.erb
<%= render 'form' %>

app/views/kittens/index.html.erb
<h1>Here are all the kittens:</h1>
<% @kittens.each do |k| %>
<div class='kitten'>
    <%= k.name %>
    <%= link_to "Put your kitty to sleep", kitten_path(k), method: :delete %>
</div>
<% end %>

app/views/kittens/new.html.erb
<%= render 'form' %>

app/views/kittens/show.html.erb
<% flash.each do |type, msg| %>
    <%= msg %>
<% end %>

Your kitten is called <%= @kitten.name %>

<%= link_to "Put your kitty to sleep", kitten_path, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittensApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>